language: bash

services:
  - docker
env:
  global:
    - DOCKER_REPO=wolvverine/docker-php
    - secure: CQ0A3FSgfa8rWlCWyTVwtdb2PWu3ihwKvijZIGY5HDx+WOKZUaLBwq9ROsesr+6z8OI0uaEJHJOScw4yBvLJ4YMFCX67cU4D+FyEp2U1MYpW8/V8SS2O7fgFqjhjG5rLWto8VEt3tiKJJFgZEMNmOR8gwejW3gGv3fs0SLD/GJ5u55aGvk5oSwdEjYNC0Bheu80ATYimx5dFvvkknvw3N7cRB/N86pEtQO+23dRFIzLTgVPWnGEIANCt2CyjHDsolcDHd3IeMtEUnGw9hU+lmqmK+Z/FEDSxk6lESyGwfzAhNKsjflkTC1nuw+Lv5BldkhMwgmvbk3SAsvIlH8a8BW8CNHl1pDHAhpAoqXOIT4FBuK9wmfrwhq+B/4zyTNyrVxxnDGPcSnjrLH54vObBmyDZOvBaw5mER8ktZWreft2iTj5N6tMSU/hMBIQ7hiMkWwTWDWEid13VBYzwRamx+ei5TXsn2VDKZhREV8Ha0ELoMWGQ+pcRF2As8tICb69EI/IKArJFCD6lV3XdrV0zuDRRJrz+pHtdIRlJSc5Hs/Y0WFEshYhUehbsT4hwkTOSjv+pQtdDMXF9pDC040z+vTIhZ+ZqLbgNe9NG/4t8K1Buojhud52pe9DeG9qfGbIqg++0SZP3HHSmV0UIZwLDsYnsgC2arFuYz9y+nx/EGvQ=
    - secure: iaA8jS1q+8h5pIPE7QkriXV6zz7sSGFY57uXV0rBGd34fNGltDBtKnUqmpgNX/hmq7e5deS6wZDswLiXS4/ZNR1s+Hp1WuQrsFa2ainA7zojEZVip9fdAJUNzpYxgfUtt+7vMhSwMdng/lHxzRBoK/I0VqXEJsq4pBrUokCEAocafyXDYO3LpcqxPg62xWBYo5fNhrmExbcWd1kd4FdMLtqpP369INAzkJJpi3ePTIocZ9ifZsWTbkItsfoJQqE+nsmOgszmU+Pax/HNvCVRS2GNbbJTKtJ5Go6b4KZuBhvWRU++KuJ1m3xjNER/Fonx8etvEuImVjV/+7YFp8T+g2OCoP7QFdxj36CXp14PuOGUupNTpw0nOkLJqQZsKB+4kMWwqd+iyPPTBmuFPE79EkQTyZD7q2aKPXgMqclSFEqutp5YVZNm789DDufw8K9HFIeq5LWfHtfQIYswXlAReCcwQQXLpR1fKYC290m+n4j6OOLhONTXgCejpbxRRakye3UDvTk/jk7wZdXdwCyC2t1f5rimP4aCB1Kisr7YoUnPSpWWTOm+aDeZruDZcP9sqYj7gledQoSNYvaVoquKXqZr6xVftvsH4UOgJ7KQpPCXP3VEX6tnvfYqIWpAVx0alB6zHgrPeOorIqKYCoqcOlOQ6h/GREOB1Tp7+pHswdk=
#  - VERSION=7.4 VARIANT=buster/cli
    - VERSION=7.4 VARIANT=buster/apache
#  - VERSION=7.4 VARIANT=buster/fpm
#  - VERSION=7.4 VARIANT=buster/zts
#  - VERSION=7.4 VARIANT=alpine3.11/cli
#  - VERSION=7.4 VARIANT=alpine3.11/fpm
#  - VERSION=7.4 VARIANT=alpine3.11/zts
#  - VERSION=7.4 VARIANT=alpine3.10/cli
#  - VERSION=7.4 VARIANT=alpine3.10/fpm
#  - VERSION=7.4 VARIANT=alpine3.10/zts
#  - VERSION=7.3 VARIANT=buster/cli
#  - VERSION=7.3 VARIANT=buster/apache
#  - VERSION=7.3 VARIANT=buster/fpm
#  - VERSION=7.3 VARIANT=buster/zts
#  - VERSION=7.3 VARIANT=stretch/cli
#  - VERSION=7.3 VARIANT=stretch/apache
#  - VERSION=7.3 VARIANT=stretch/fpm
#  - VERSION=7.3 VARIANT=stretch/zts
#  - VERSION=7.3 VARIANT=alpine3.11/cli
#  - VERSION=7.3 VARIANT=alpine3.11/fpm
#  - VERSION=7.3 VARIANT=alpine3.11/zts
#  - VERSION=7.3 VARIANT=alpine3.10/cli
#  - VERSION=7.3 VARIANT=alpine3.10/fpm
#  - VERSION=7.3 VARIANT=alpine3.10/zts
#  - VERSION=7.2 VARIANT=buster/cli
#  - VERSION=7.2 VARIANT=buster/apache
#  - VERSION=7.2 VARIANT=buster/fpm
#  - VERSION=7.2 VARIANT=buster/zts
#  - VERSION=7.2 VARIANT=stretch/cli
#  - VERSION=7.2 VARIANT=stretch/apache
#  - VERSION=7.2 VARIANT=stretch/fpm
#  - VERSION=7.2 VARIANT=stretch/zts
#  - VERSION=7.2 VARIANT=alpine3.11/cli
#  - VERSION=7.2 VARIANT=alpine3.11/fpm
#  - VERSION=7.2 VARIANT=alpine3.11/zts
#  - VERSION=7.2 VARIANT=alpine3.10/cli
#  - VERSION=7.2 VARIANT=alpine3.10/fpm
#  - VERSION=7.2 VARIANT=alpine3.10/zts

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="php:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images
#publish:
  - pwd
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" ] && ~/build/Wolvverine/docker-php/publish.sh'

# vim:set et ts=2 sw=2:
